### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by weotch** [BKWLD/vue-in-view#1]
## Major functionality

- [ ] Add events API

  ```pug 
  in-view(@visible='visible = true)
  ```

- [ ] Add scoped slots API

  ```pug
  in-view: template(#default='{ visible }')
    transition(name='fade'): div(v-if='visible') Hello World
  ```

- [ ] Add css class API

  ```pug
  //- Adds `in-view` class to the `div`
  in-view(classes): div Hello World
  ```

- [ ] Create `in-view-layout-mixin` and `appear` prop to initially set `in-view` class and then remove it for any components that weren't in the initial viewport once JS hydrates.  This is so css animation based animations will play before JS hydrates for components that are above the fold and the rest will play when scrolled into the viewport.

  ```pug 
  in-view(classes appear)
  ```

## Other tasks

- [x] Make demo site using `@cloak-app/demo-theme`
- [ ] Support `above` and `below`
- [ ] Support `fully`
- [ ] Support `once`
- [ ] Support customizing `IntersectionObserver` options
- [ ] Make Nuxt module for setting global defaults

## Similar packages:

- https://github.com/Akryum/vue-observe-visibility - Directive only
- https://github.com/heavyy/vue-intersect - Events only
- https://github.com/tennisgent/vue-intersection - Heavy API
- https://github.com/BiYuqi/vue-intersection-observer - Events only
- https://github.com/megurock/vue-intersect-directive - Directive only

**Comment by weotch** [comment]
Replacing this with #2
