### ISSUE TITLE
1.0 Todo List

### ISSUE THREAD

**Issue by weotch** [BKWLD/vue-in-view#2]
- [x] Implement `classes` prop
- [x] Make demo of animate
- [x] Make demo of scoped slots
- [x] Make demo of events
- [x] Make demo of once
- [x] Make demo of `classes`
- [ ] Support customizing IntersectionObserver options
- [ ] Add Nuxt module API for setting defaults (like set publicRuntime configs that are used, if present, by default functions of the props)
